### ISSUE TITLE
iPhone 8 Plus sees "weak phone" warning

### ISSUE THREAD

**Issue by joachimneumann** [ManfredKarrer/bisq-desktop#10]
<img width="458" alt="screen shot 2018-07-16 at 19 37 08" src="https://user-images.githubusercontent.com/5642225/42775339-68e5439e-8934-11e8-957a-f2e79173db48.png">

**Comment by ManfredKarrer** [comment]
upps...

**Comment by joachimneumann** [comment]
Wo du gerade dabei bist kannst Du ja gleich das iPhone 6s mit zu den guten iPhone tun

**Comment by ManfredKarrer** [comment]
Yes I will add tests for all and enable beside iphone 6 and below.
I just tested with hard coded "iPhone 8 Plus" string but i cannot reproduce the bug.

**Comment by ManfredKarrer** [comment]
Closed as fixed.
