### ISSUE TITLE
Usability: use mirror image for QR code scanning feedback image

### ISSUE THREAD

**Issue by bunkenburg** [ManfredKarrer/bisq-desktop#11]
<img width="1284" alt="screen shot 2018-07-16 at 19 37 23" src="https://user-images.githubusercontent.com/806861/42808511-cc397c06-89b3-11e8-8e41-a9f5ed255480.png">

Steps to reproduce:
* invoke the "Scan QR code" functionality from desktop app in order to pair with phone app
* in the desktop app, see live image from camera
* user tries to hold phone in front of camera. Maybe they hold it too much to the right

Observed:
* user moves phone to the left
* on the image, phone moves even further away

Expected:
* user moves phone to the left
* on the image, phone move in expected direction

The problem is that the user expects the image to behave like a mirror. The self-video image of skype (and similar) is a mirror image, so it behaves according to user expectation. (The skype image of the remote partner is not mirror image.)

So I suggest, for better usability, to turn around the image on the feedback, so that it is easier for the user to move the phone to the right place. The image that will be passed to parsing of the QR code must not be turned around, so that QR scanning is not affected.

**Comment by ManfredKarrer** [comment]
Thanks for the proposal!

**Comment by ManfredKarrer** [comment]
Implemented with https://github.com/bisq-network/bisq-desktop/pull/1635
